name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**.go'
              - 'go.mod'
              - 'go.sum'

  lint:
    needs: check-changes
    if: needs.check-changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"
          cache: true

      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Check go fix
        run: |
          diff=$(go fix -diff ./...)
          if [ -n "$diff" ]; then
            echo "$diff"
            echo "Run 'go fix ./...' locally."
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.9.0

      - name: Check format
        run: |
          golangci-lint fmt ./...
          git diff --exit-code

  test:
    needs: check-changes
    if: needs.check-changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"
          cache: true

      - name: Run tests
        run: go test -count=1 ./...

  required-checks:
    needs: [lint, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(needs) }}' \
            | jq -e 'all(
                .[]; .result == "success"
                  or .result == "skipped"
              )'
